OFFICIAL_STORE_DEALS = {
    "Crimson Desert": [
        {
            "store": "Steam",
            "title": "Crimson Desert",
            "price_eur": 69.99,
            "condition": "digital",
            "shipping_eur": 0.0,
            "availability": "available",
            "trust_score": 1.0,
            "source_type": "official",
        },
        {
            "store": "Epic Games Store",
            "title": "Crimson Desert",
            "price_eur": 69.99,
            "condition": "digital",
            "shipping_eur": 0.0,
            "availability": "available",
            "trust_score": 1.0,
            "source_type": "official",
        },
        {
            "store": "GOG",
            "title": "Crimson Desert",
            "price_eur": 59.99,
            "condition": "digital",
            "shipping_eur": 0.0,
            "availability": "available",
            "trust_score": 1.0,
            "source_type": "official",
        },
    ],
    "PlayStation 5 Disc Edition": [
        {
            "store": "PlayStation Direct",
            "title": "PlayStation 5 Disc Edition",
            "price_eur": 549.99,
            "condition": "new",
            "shipping_eur": 0.0,
            "availability": "available",
            "trust_score": 1.0,
            "source_type": "official",
        },
        {
            "store": "Best Buy",
            "title": "PlayStation 5 Disc Edition",
            "price_eur": 529.99,
            "condition": "new",
            "shipping_eur": 9.99,
            "availability": "available",
            "trust_score": 1.0,
            "source_type": "official",
        },
        {
            "store": "GameStop",
            "title": "PlayStation 5 Disc Edition",
            "price_eur": 499.99,
            "condition": "refurbished",
            "shipping_eur": 14.99,
            "availability": "available",
            "trust_score": 1.0,
            "source_type": "official",
        },
    ],
    "PlayStation 5 Digital Edition": [
        {
            "store": "PlayStation Direct",
            "title": "PlayStation 5 Digital Edition",
            "price_eur": 449.99,
            "condition": "new",
            "shipping_eur": 0.0,
            "availability": "available",
            "trust_score": 1.0,
            "source_type": "official",
        },
        {
            "store": "Best Buy",
            "title": "PlayStation 5 Digital Edition",
            "price_eur": 439.99,
            "condition": "new",
            "shipping_eur": 9.99,
            "availability": "available",
            "trust_score": 1.0,
            "source_type": "official",
        },
    ],
}

AUTHORIZED_RESELLER_DEALS = {
    "Crimson Desert": [
        {
            "store": "Green Man Gaming",
            "title": "Crimson Desert",
            "price_eur": 54.99,
            "condition": "digital key",
            "shipping_eur": 0.0,
            "availability": "available",
            "trust_score": 0.8,
            "source_type": "authorized_reseller",
        },
        {
            "store": "Fanatical",
            "title": "Crimson Desert",
            "price_eur": 52.99,
            "condition": "digital key",
            "shipping_eur": 0.0,
            "availability": "available",
            "trust_score": 0.8,
            "source_type": "authorized_reseller",
        },
    ],
    "Crimson Desert Deluxe Edition": [
        {
            "store": "Fanatical",
            "title": "Crimson Desert Deluxe Edition",
            "price_eur": 64.99,
            "condition": "digital key",
            "shipping_eur": 0.0,
            "availability": "available",
            "trust_score": 0.8,
            "source_type": "authorized_reseller",
        }
    ],
}

GRAY_MARKET_DEALS = {
    "Crimson Desert": [
        {
            "store": "G2A",
            "title": "Crimson Desert",
            "price_eur": 41.00,
            "condition": "digital key",
            "shipping_eur": 0.0,
            "availability": "available",
            "trust_score": 0.4,
            "source_type": "gray_market",
            "warning": "High risk of revocation or region lock.",
        },
        {
            "store": "Kinguin",
            "title": "Crimson Desert",
            "price_eur": 39.99,
            "condition": "digital key",
            "shipping_eur": 0.0,
            "availability": "available",
            "trust_score": 0.3,
            "source_type": "gray_market",
            "warning": "High risk of revocation or region lock.",
        },
    ]
}

MARKETPLACE_DEALS = {
    "PlayStation 5 Disc Edition": [
        {
            "store": "Facebook Marketplace",
            "title": "PlayStation 5 Disc Edition",
            "price_eur": 380.00,
            "condition": "used - like new",
            "shipping_eur": 0.0,
            "availability": "pickup today",
            "trust_score": 0.8,
            "source_type": "marketplace",
            "distance_km": 5.0,
            "seller_rating": 4.8,
        },
        {
            "store": "eBay Local",
            "title": "PlayStation 5 Disc Edition",
            "price_eur": 420.00,
            "condition": "used - good",
            "shipping_eur": 0.0,
            "availability": "pickup tomorrow",
            "trust_score": 0.7,
            "source_type": "marketplace",
            "distance_km": 18.0,
            "seller_rating": 4.7,
        },
        {
            "store": "OfferUp",
            "title": "PlayStation 5 Disc Edition",
            "price_eur": 395.00,
            "condition": "used - very good",
            "shipping_eur": 0.0,
            "availability": "pickup today",
            "trust_score": 0.75,
            "source_type": "marketplace",
            "distance_km": 12.0,
            "seller_rating": 4.6,
        },
    ],
    "PlayStation 5 Digital Edition": [
        {
            "store": "Facebook Marketplace",
            "title": "PlayStation 5 Digital Edition",
            "price_eur": 330.00,
            "condition": "used - very good",
            "shipping_eur": 0.0,
            "availability": "pickup today",
            "trust_score": 0.8,
            "source_type": "marketplace",
            "distance_km": 6.0,
            "seller_rating": 4.8,
        },
        {
            "store": "OfferUp",
            "title": "PlayStation 5 Digital Edition",
            "price_eur": 345.00,
            "condition": "used - good",
            "shipping_eur": 0.0,
            "availability": "pickup tomorrow",
            "trust_score": 0.74,
            "source_type": "marketplace",
            "distance_km": 10.0,
            "seller_rating": 4.5,
        },
    ],
}
